services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_orders:
    image: postgres:15
    container_name: shop-postgres-orders
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  postgres_payments:
    image: postgres:15
    container_name: shop-postgres-payments
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"

  api-gateway:
    image: nginx:alpine
    container_name: shop-gateway
    volumes:
      - ./ApiGateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - order-service
      - payment-service

  order-service:
    build: 
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: shop-order-service
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_orders;Database=orders_db;Username=user;Password=password"
      RabbitMq__HostName: rabbitmq
    ports:
      - "8081:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_orders:
        condition: service_started

  payment-service:
    build: 
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: shop-payment-service
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres_payments;Database=payments_db;Username=user;Password=password"
      RabbitMq__HostName: rabbitmq
    ports:
      - "8082:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres_payments:
        condition: service_started

  frontend:
    build: 
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: shop-frontend
    environment:
      GatewayUrl: "http://api-gateway:80"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5000:80"
    depends_on:
      - api-gateway
